# Generated by Django 4.2.3 on 2023-12-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0004_delete_inventory'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'size', 'color')},
        ),
    ]
