# Generated by Django 4.2.3 on 2023-11-30 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_access', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(default='processing', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='ordering.OrderItem', to='data_access.product'),
        ),
    ]
