# Generated by Django 4.2.6 on 2023-11-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
    ]
