# Generated by Django 4.2.6 on 2023-11-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
