# Generated by Django 4.2.3 on 2023-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0004_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
